### ISSUE TITLE
Specify components

### ISSUE THREAD

**Issue by xrotwang** [glottobank/cldf#19]
Components could be specified as orthogonal aspect to modules. I.e. pieces of specification which can be reused across modules. Candidates include:
- examples in IGT
- forms (could be re-used by dictionary, wordlist, and potentially even structure-dataset)

In terms of architecture, components could just be `Table` descriptions - as opposed to modules, which are `TableGroup` descriptions.

**Comment by LinguList** [comment]
I started working on this by showing one of the most complete examples of annotation I have so far:

* https://github.com/LinguList/cldf/tree/master/examples/wordlist

This ships with an example.tsv (which can be parsed by LingPy), and the metadata.json.

I stumbled over one problem regarding basic datatypes: We have types which are nested two times, i.e., a sequence in the column Segments would first be separated into morphemes using the " + " delimiter and then the pieces would be split into segments using the " " delimiter. Is this something we need to handle by writing our own specifications, or by code which checks content? So far, I don't expect we will go beyond this, but the doubly nested lists are essential for partial cognates and alignments of partial cognate sets. If they are handled initially, this would be useful for evaluation, since:

* partial alignments have the same length in the first dimension as partial cognate sets and as segments.
* the column Morphemes, which is space-delimited, has the same length as Segments, Partial Alignments, and Partial Cognate sets in their first dimension (in practice: length of morphemes must be <= length of alignments/etc., as we allow for unannotated parts).

**Comment by xrotwang** [comment]
I guess the best we can do inside of the csvw spec is
```python
{
    "name": "segments",
    "separator": "+",
    "datatype": {
        "base": "string",
        "format": "([\\S]+)( [\\S]+)*"
    }
}
```
so the second layer of nesting is not parsed when reading the CSV, but at least validated to be parseable.

**Comment by xrotwang** [comment]
Special handling by `pycldf` could still be made somewhat generic, if we would let `pycldf` recognize certain `propertyUrl`s for columns. E.g. in the case of segments, a `propertyUrl` of `http://linguistics-ontology.org/gold/2010/Segment` could be interpreted as a datatype with double nesting, so each item of the first-level list would be split again using ` ` as delimiter.

**Comment by xrotwang** [comment]
For things like partial cognate sets, we'd have to mint property URLs ourselves, though.

**Comment by xrotwang** [comment]
See https://github.com/glottobank/cldf/blob/master/faq.md#how-can-i-specify-tertiary-separators-for-csv-files
